### ISSUE TITLE
Doesn't work on Python 3.9.1

### ISSUE THREAD

**Issue by ThomasWhatt** [juhasch/PhysicalQuantities#123]
Hi! I am using Python 3.9.1 with Spyder 4.2.1 and command %load_ext PhysicalQuantities.ipython in Spyder console gives the following problem
![spyder_problem](https://user-images.githubusercontent.com/53299571/102778339-75cc8500-43a3-11eb-8373-5e1137345165.jpg)
What should/can I do to solve it? (other tryings with different commands gave me no positive result)
Thanks!

**Comment by juhasch** [comment]
I pushed some fixes in PR#124. It works for me using Python 3.9 and IPython 7.19.0
Does this solve your problems ?

**Comment by ThomasWhatt** [comment]
Sorry, I am quite newcomer as a GitHub user - could you please explain what PR#124 means? Thank you :)

**Comment by juhasch** [comment]
OK, sure. You can try to install the most recent version using the `pip` command:
`pip install git+https://github.com/juhasch/PhysicalQuantities.git`
