### ISSUE TITLE
Bohr unit still using pi as a unit

### ISSUE THREAD

**Issue by Aphit** [juhasch/PhysicalQuantities#31]
The line below throws out an error because it's trying to use pi as a unit, and it is not using np.pi as you've changed others to.

     addunit('Bohr', '4*pi*eps0*hbar**2/me/e0**2', 'Bohr radius')

Error:

     NameError: name 'pi' is not defined

Also, it looks like hartree is the the same.

**Comment by juhasch** [comment]
The additional units defined in `more_units.py` are currently not working as expected, as you have found out. The reason is mixing constants and units does not alway work.
